# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27df3a292914da331d3e7b0e7c15e5043ea876065725f0833431dbe25b29c486dd7e1a61a56fc7da3ac1238b042a7e2b0ff62f66386ef03046eeb385fe4e4447

test:
  secret_key_base: cec65ee296a4d1c22c84f7e764f619079a24540e85e18b404bcbf2a0ae1f1853e86c31fa3c949263aa9a87ecde7d4d49a54c4b29d84b9cbf2bc28e5269bf7fa6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
